# Generated by Django 3.2.2 on 2021-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='update',
            field=models.DateTimeField(null=True),
        ),
    ]
