# Generated by Django 3.2.2 on 2021-05-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='following',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='network.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followersuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
