# Generated by Django 3.2.2 on 2021-05-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210520_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='following',
        ),
    ]
