# Generated by Django 3.2.2 on 2021-05-10 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210510_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='added',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='added',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='added',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
