# Generated by Django 3.2.2 on 2021-05-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210510_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='category',
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingimageurl', models.URLField()),
                ('listingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingimageurl', to='auctions.auctionlistings')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('arm', 'Armor'), ('wea', 'Weapon'), ('ite', 'Item'), ('alc', 'Alchemy')], max_length=3)),
                ('listingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingcategory', to='auctions.auctionlistings')),
            ],
        ),
    ]
