# Generated by Django 3.2.2 on 2021-05-10 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210510_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='listedby', to='auctions.user'),
            preserve_default=False,
        ),
    ]
