# Generated by Django 3.2.2 on 2021-05-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlistings_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='userid',
        ),
    ]
