# Generated by Django 3.2.2 on 2021-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlistings_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='listingimageurl',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageURL',
        ),
    ]
