# Generated by Django 3.2.2 on 2021-05-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210510_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='userid',
            new_name='user',
        ),
    ]
