# Generated by Django 3.2.2 on 2021-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_userid_auctionlistings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
