# Generated by Django 3.2.2 on 2021-05-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210510_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='listing',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listingid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listingid',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('arm', 'Armor'), ('wea', 'Weapon'), ('ite', 'Item'), ('alc', 'Alchemy')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='listingbid', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='listingcomment', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
