# Generated by Django 3.2.2 on 2021-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210510_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='listingimageurl',
            field=models.URLField(blank=True),
        ),
    ]
