# Generated by Django 3.2.2 on 2021-05-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_activelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelisting',
            name='winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='userwon', to='auctions.user'),
            preserve_default=False,
        ),
    ]
